name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "feature/integration-modele" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # JOB 1 : TESTS (Se lance sur toutes les branches)
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3
        with:
          lfs: true  

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Installer les dépendances
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lancer les tests
        run: python -m pytest

  # JOB 2 : DEPLOIEMENT
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0     # Indispensable pour l'historique
          lfs: true          # Active le support LFS

      - name: Push vers Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Initialisation
          git lfs install
          
          # 2. LA COMMANDE MAGIQUE : On force le téléchargement BRUT depuis GitHub
          # Cela remplit le cache .git/lfs/objects nécessaire pour le push
          git lfs fetch --all origin
          
          # 3. On tire les fichiers dans le dossier de travail (sécurité)
          git lfs pull
          
          # 4. Configuration Git
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # 5. Ajout du remote Hugging Face
          git remote add space https://fii08:$HF_TOKEN@huggingface.co/spaces/fii08/Energy-Predictor-P5
          
          # 6. Envoi Force
          git push --force space main